10-chp.serverui/2-action/lib/plate_slate_web/router.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlateWeb.Router do
  use PlateSlateWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PlateSlateWeb.Context
  end

  scope "/admin", PlateSlateWeb do
    pipe_through :browser

    resources "/items", ItemController
  end

  scope "/" do
    pipe_through :api

    forward "/api", Absinthe.Plug,
      schema: PlateSlateWeb.Schema

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: PlateSlateWeb.Schema,
      socket: PlateSlateWeb.UserSocket
  end

end

10-chp.serverui/2-action/lib/plate_slate/menu/item.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlate.Menu.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias PlateSlate.Menu.Item


  schema "items" do
    field :added_on, :date
    field :description, :string
    field :name, :string
    field :price, :decimal
    field :allergy_info, {:array, :map}

    belongs_to :category, PlateSlate.Menu.Category

    many_to_many :tags, PlateSlate.Menu.ItemTag,
      join_through: "items_taggings"

    timestamps()
  end

  @doc false
  def changeset(%Item{} = item, attrs) do
    item
    |> cast(attrs, [:name, :description, :price, :added_on])
    |> validate_required([:name, :price])
    |> foreign_key_constraint(:category)
    |> unique_constraint(:name)
  end
end

10-chp.serverui/2-action/lib/plate_slate/ordering/item.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlate.Ordering.Item do
  use Ecto.Schema
  import Ecto.Changeset

  embedded_schema do
    field :price, :decimal
    field :name, :string
    field :quantity, :integer
  end

  def changeset(item, attrs) do
    item
    |> cast(attrs, [:price, :name, :quantity])
    |> validate_required([:price, :name, :quantity])
  end
end

10-chp.serverui/2-action/lib/plate_slate_web/controllers/item_controller.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlateWeb.ItemController do
  use PlateSlateWeb, :controller
  use Absinthe.Phoenix.Controller,
    schema: PlateSlateWeb.Schema

  @graphql """
  query Index @action(mode: INTERNAL) {
    menu_items
  }
  """
  def index(conn, result) do
    result |> IO.inspect
    render(conn, "index.html", items: result.data.menu_items)
  end
end

10-chp.serverui/2-action/lib/plate_slate_web/views/item_view.ex
#---
# Excerpted from "Craft GraphQL APIs in Elixir with Absinthe",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit http://www.pragmaticprogrammer.com/titles/wwgraphql for more book information.
#---
defmodule PlateSlateWeb.ItemView do
  use PlateSlateWeb, :view
end

10-chp.serverui/2-action/lib/plate_slate_web/templates/item/edit.html.eex
<h2>Edit Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :update, @item)) %>

<span><%= link "Back", to: item_path(@conn, :index) %></span>

10-chp.serverui/2-action/lib/plate_slate_web/templates/item/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

10-chp.serverui/2-action/lib/plate_slate_web/templates/item/index.html.eex
<h2>Listing Items</h2>

<table class="table">
  <thead>
    <tr>
      <th>Menu Item</th>
    </tr>
  </thead>
  <tbody>
<%= for item <- @items do %>
    <tr>
      <td><%= item.name %></td>
      <td class="text-right">
        <span><%= link "Show", to: item_path(@conn, :show, item),
          class: "btn btn-default btn-xs" %>
        </span>
        <span><%= link "Edit", to: item_path(@conn, :edit, item),
          class: "btn btn-default btn-xs" %>
        </span>
        <span><%= link "Delete", to: item_path(@conn, :delete, item),
          method: :delete,
          data: [confirm: "Are you sure?"],
          class: "btn btn-danger btn-xs" %>
        </span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

10-chp.serverui/2-action/lib/plate_slate_web/templates/item/new.html.eex
<h2>New Item</h2>

<%= render "form.html", Map.put(assigns, :action, item_path(@conn, :create)) %>

<span><%= link "Back", to: item_path(@conn, :index) %></span>

10-chp.serverui/2-action/lib/plate_slate_web/templates/item/show.html.eex
<h2>Show Item</h2>

<ul>

</ul>

<span><%= link "Edit", to: item_path(@conn, :edit, @item) %></span>
<span><%= link "Back", to: item_path(@conn, :index) %></span>